# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvVZzpCwTcnZYXs1FGynyJH1DKrmC3H4
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle
import warnings
import os

warnings.filterwarnings("ignore")

# --- Load model and scaler safely ---
try:
    with open("model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("scaler.pkl", "rb") as f:
        scaler = pickle.load(f)
except Exception as e:
    st.error(f"Error loading model or scaler: {e}")

import os
import pickle
model_path = "model.pkl"
scaler_path = "scaler.pkl"
with open(model_path, "rb") as f:
    model = pickle.load(f)

with open(scaler_path, "rb") as f:
    scaler = pickle.load(f)

